BookshopUi/Controllers/BookingController.cs
using BookshopUi.Services;
using Commons.Models;
using Commons.Services;
using Microsoft.AspNetCore.Mvc;
using RestSharp;

namespace BookshopUi.Controllers;

public class BookingController : BookShopController
{
    private readonly IBookingApiService _bookingApiService;

    public BookingController(IBookingApiService bookingApiService, IValidationService validationService) : base(
        validationService)
    {
        _bookingApiService = bookingApiService ?? throw new ArgumentNullException(nameof(bookingApiService)); ;
        _bookingApiService.SetClient(new RestClient(Constants.ApiUrl));
    }

    public async Task<IActionResult> Index()
    {
        IEnumerable<Booking> allBookings;

        if (IsManager)
        {
            _bookingApiService.AddTokenToHeader(ValidationModel.Token);
            allBookings = await _bookingApiService.GetAllBookings();
            return View(allBookings);
        }

        if (IsCustomer)
        {
            _bookingApiService.AddTokenToHeader(ValidationModel.Token);
            allBookings = await _bookingApiService.GetAllBookings(ValidationModel.Id);
            return View(allBookings);
        }

        return RedirectToAction("Forbidden", "User");
    }

    public IActionResult Create()
    {
        if (IsManager)
        {
            return View();
        }

        return RedirectToAction("Forbidden", "User");
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(Booking booking)
    {
        if (IsManager)
        {
            _bookingApiService.AddTokenToHeader(ValidationModel.Token);
            await _bookingApiService.PostBooking(booking);
            SuccessNotification("Booking created successfully");
            return RedirectToAction(nameof(Index));
        }

        return RedirectToAction("Forbidden", "User");
    }

    public async Task<IActionResult> Edit(int id)
    {
        if (IsManager)
        {
            if (id == 0)
            {
                return NotFound();
            }

            _bookingApiService.AddTokenToHeader(ValidationModel.Token);
            var bookingFromDb = await _bookingApiService.GetBooking(id);
            if (bookingFromDb == null)
            {
                return NotFound();
            }

            return View(bookingFromDb);
        }

        return RedirectToAction("Forbidden", "User");
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(Booking booking)
    {
        if (IsManager)
        {
            _bookingApiService.AddTokenToHeader(ValidationModel.Token);
            await _bookingApiService.UpdateBooking(booking);
            SuccessNotification("Booking updated successfully");
            return RedirectToAction(nameof(Index));
        }

        return RedirectToAction("Forbidden", "User");
    }

    public async Task<IActionResult> Delete(int id)
    {
        if (IsManager)
        {
            if (id == 0)
            {
                return NotFound();
            }

            _bookingApiService.AddTokenToHeader(ValidationModel.Token);
            var bookingFromDb = await _bookingApiService.GetBooking(id);
            if (bookingFromDb == null)
            {
                return NotFound();
            }

            return View(bookingFromDb);
        }

        return RedirectToAction("Forbidden", "User");
    }

    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeletePost(int id)
    {
        if (IsManager)
        {
            _bookingApiService.AddTokenToHeader(ValidationModel.Token);
            var productFromDb = await _bookingApiService.GetBooking(id);
            if (productFromDb == null)
            {
                return NotFound();
            }

            await _bookingApiService.DeleteBooking(id);
            SuccessNotification("Booking deleted successfully");
            return RedirectToAction(nameof(Index));
        }

        return RedirectToAction("Forbidden", "User");
    }
}

BookshopUi/Controllers/ProductController.cs
using BookshopUi.Services;
using Commons.Models;
using Commons.Services;
using Microsoft.AspNetCore.Mvc;
using RestSharp;

namespace BookshopUi.Controllers
{
    public class ProductController : BookShopController
    {
        private readonly IProductApiService _productApiService;

        public ProductController(IProductApiService productApiService, IValidationService validationService) : base(
            validationService)
        {
            _productApiService = productApiService;
            _productApiService.SetClient(new RestClient(Constants.ApiUrl));
        }

        public async Task<IActionResult> Index()
        {
            if (IsManager || IsCustomer)
            {
                _productApiService.AddTokenToHeader(ValidationModel.Token);
                var productsList = await _productApiService.GetAllProducts();
                return View(productsList);
            }

            return RedirectToAction("Forbidden", "User");
        }

        public IActionResult Create()
        {
            if (IsManager)
            {
                return View();
            }

            return RedirectToAction("Forbidden", "User");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Product product)
        {
            if (IsManager)
            {
                if (ModelState.IsValid)
                {
                    _productApiService.AddTokenToHeader(ValidationModel.Token);
                    await _productApiService.PostProduct(product);
                    SuccessNotification("Product created successfully");
                    return RedirectToAction(nameof(Index));
                }

                return View(product);
            }

            return RedirectToAction("Forbidden", "User");
        }

        public async Task<IActionResult> Edit(int id)
        {
            if (IsManager)
            {
                if (id == 0)
                {
                    return NotFound();
                }

                _productApiService.AddTokenToHeader(ValidationModel.Token);
                var productFromDb = await _productApiService.GetProduct(id);
                if (productFromDb == null)
                {
                    return NotFound();
                }

                return View(productFromDb);
            }

            return RedirectToAction("Forbidden", "User");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Product product)
        {
            if (IsManager)
            {
                if (ModelState.IsValid)
                {
                    _productApiService.AddTokenToHeader(ValidationModel.Token);
                    await _productApiService.UpdateProduct(product);
                    SuccessNotification("Product updated successfully");
                    return RedirectToAction(nameof(Index));
                }

                return View(product);
            }

            return RedirectToAction("Forbidden", "User");
        }

        public async Task<IActionResult> Delete(int id)
        {
            if (IsManager)
            {
                if (id == 0)
                {
                    return NotFound();
                }

                _productApiService.AddTokenToHeader(ValidationModel.Token);
                var productFromDb = await _productApiService.GetProduct(id);
                if (productFromDb == null)
                {
                    return NotFound();
                }

                return View(productFromDb);
            }

            return RedirectToAction("Forbidden", "User");
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeletePost(int id)
        {
            if (IsManager)
            {
                _productApiService.AddTokenToHeader(ValidationModel.Token);
                var productFromDb = await _productApiService.GetProduct(id);
                if (productFromDb == null)
                {
                    return NotFound();
                }
                
                await _productApiService.DeleteProduct(id);
                SuccessNotification("Product delete successfully");
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction("Forbidden", "User");
        }
    }
}

BookshopUi/Controllers/UserController.cs
using BookshopUi.Services;
using Commons.Models;
using Commons.Services;
using Microsoft.AspNetCore.Mvc;
using RestSharp;

namespace BookshopUi.Controllers;

public class UserController : BookShopController
{
    private readonly IUserApiService _userApiService;

    public UserController(IUserApiService userApiService, IValidationService validationService) : base(
        validationService)
    {
        _userApiService = userApiService;
        _userApiService.SetClient(new RestClient(Constants.ApiUrl));
    }

    public async Task<IActionResult> Index()
    {
        IEnumerable<User> userList;
        if (IsAdmin)
        {
            _userApiService.AddTokenToHeader(ValidationModel.Token);
            userList = await _userApiService.GetAllUsers();
            return View(userList);
        }

        if (IsCustomer)
        {
            _userApiService.AddTokenToHeader(ValidationModel.Token);
            var user = await _userApiService.GetUser(ValidationModel.Id);
            userList = new List<User>() { user };
            return View(userList);
        }

        return RedirectToAction(nameof(Forbidden));
    }

    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(User user)
    {
        if (ModelState.IsValid)
        {
            await _userApiService.PostUser(user);
            SuccessNotification("User created successfully");

            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction(nameof(Index), "Home");
            }

            return RedirectToAction(nameof(Index));
        }

        return View(user);
    }

    public async Task<IActionResult> Edit(int id)
    {
        if (id == 0)
        {
            return NotFound();
        }

        if (IsAdmin || IsCustomer)
        {
            if (IsCustomer && ValidationModel.Id != id)
                return RedirectToAction(nameof(Forbidden));

            _userApiService.AddTokenToHeader(ValidationModel.Token);
            var userFromDb = await _userApiService.GetUser(id);
            if (userFromDb == null)
            {
                return NotFound();
            }

            return View(userFromDb);
        }

        return Unauthorized();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(User user)
    {
        if ((IsAdmin || IsCustomer) && ModelState.IsValid)
        {
            _userApiService.AddTokenToHeader(ValidationModel.Token);
            await _userApiService.UpdateUser(user);
            SuccessNotification("User updated successfully");
            return RedirectToAction(nameof(Index));
        }

        return View(user);
    }

    public async Task<IActionResult> Delete(int id)
    {
        if (id == 0)
        {
            return NotFound();
        }

        if (IsAdmin || IsCustomer)
        {
            if (IsCustomer && ValidationModel.Id != id)
                return RedirectToAction("Forbidden");

            _userApiService.AddTokenToHeader(ValidationModel.Token);
            var userFromDb = await _userApiService.GetUser(id);
            if (userFromDb == null)
            {
                return NotFound();
            }

            return View(userFromDb);
        }

        return Unauthorized();
    }

    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeletePost(int id)
    {
        if (IsAdmin || IsCustomer)
        {
            if (IsCustomer && ValidationModel.Id != id)
                return RedirectToAction("Forbidden");
            _userApiService.AddTokenToHeader(ValidationModel.Token);
            var userFromDb = await _userApiService.GetUser(id);
            if (userFromDb == null)
            {
                return NotFound();
            }

            await _userApiService.DeleteUser(id);
            SuccessNotification("User deleted successfully");
            return RedirectToAction(nameof(Index));
        }

        return Unauthorized();
    }

    public IActionResult Forbidden()
    {
        return View();
    }
}

BookshopUi/Views/Shared/_Layout.cshtml
@using System.Security.Claims
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - BookshopUi</title>
    <link rel="stylesheet" href="~/css/bootswatchTheme.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/BookshopUi.styles.css" asp-append-version="true"/>
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">BookshopUi</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarColor02">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    
                    @if (User.Identity.IsAuthenticated)
                    {
                        if (User.IsInRole("Admin") || User.IsInRole("Customer"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                            </li>
                        }

                        if (User.IsInRole("Manager") || User.IsInRole("Customer"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Product" asp-action="Index" id="product_link">Products</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Booking" asp-action="Index">Bookings</a>
                            </li>
                        }
                    }

                </ul>
                @if (User.Identity.IsAuthenticated)
                {
                    <div class="mx-auto" role="group">
                        <a asp-controller="Home" asp-action="LogOut" id="logout"><i class="bi bi-box-arrow-right"></i> Log out</a>
                    </div>
                }

            </div>
        </div>
    </nav>

</header>
<div class="container">
    <main role="main" class="pb-3">
        <partial name="_Notification"/>
        @RenderBody()
    </main>
</div>

<footer class="footer text-muted bg-dark">
    <div class="container">
        &copy; 2023 - BookshopUi
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BookshopUi/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    
    <script type="text/javascript">
    toastr.success('@TempData["success"]');
    </script>
}
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["error"]');
        </script>
}